export enum Actions {
  GET_TABLE_DATA = 'GET_TABLE_DATA',
  SET_TABLE_FILTER = 'SET_TABLE_FILTER',
  CHANGE_AMOUNT = 'CHANGE_AMOUNT',
  OPEN_MODAL = 'OPEN_MODAL',
  CLOSE_MODAL = 'CLOSE_MODAL',
  GET_MODAL_PRODUCTS = 'GET_MODAL_PRODUCTS',
  REPLACE_ITEM = 'REPLACE_ITEM',
  SEARCH = 'SEARCH',
}
